version: '3.9'
services:
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    ports:
      - 8080:8080
      - 50000:50000
    restart: on-failure
    container_name: jenkins
    volumes:
      - jenkins_home:/var/jenkins_home
volumes:
  jenkins_home: null
